site_name: مستندات فنی نوآوران ابر آبی
site_author: گروه فنی و توسعه نوآوران ابر آبی
site_url: https://docs.bidev.ir

repo_url: https://github.com/blue-innovators/noavaran-docs
repo_name: noavaran-docs
edit_uri: edit/master/docs/

nav:
  - خانه:
    - index.md
  - راهنمای زیرساخت:
    - infrastructure/setup-linux-server.md
    - infrastructure/setup-apps.md
  - راهنمای Common:
    - common-index.md
    - سیستم Notification:
      - notification/notification-commands.md
      - notification/notification-apis.md
    - سیستم Payment:
      - payment/payment-commands.md
    
theme:
  name: material
  language: fa
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  font:
    text: vazir
    code: Roboto Mono
  palette:
    scheme: slate
    primary: indigo
    accent: pink

extra_css:
  - assets/styles.css

markdown_extensions:
#   - toc:
#       permalink: "#"
#   - smarty
  - admonition
#  - attr_list
  - footnotes
#   - codehilite
#   - pymdownx.arithmatex
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_generator: !!python/name:pymdownx.emoji.to_svg
#   - pymdownx.inlinehilite
#   - pymdownx.magiclink
#   - pymdownx.mark
#   - pymdownx.smartsymbols
  - pymdownx.superfences
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde
#   - fontawesome_markdown
